// Generated by nuxi
/// <reference types="@nuxtjs/stylelint-module" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="cookie-universal-nuxt" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path="types/nitro.d.ts" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference types="unplugin-vue2-script-setup/types" />
/// <reference path="types/auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
